import React, { useEffect, useState } from 'react';
import { api, formatDate } from '../api.js';
import { Button, Card } from '../components/UI.jsx';

export function LinkWebsiteRecordButton({ resource, record }) {
  const [busy, setBusy] = useState(false), [message, setMessage] = useState('');
  if (!['students', 'applications', 'financials', 'events'].includes(resource) || !record._id) return null;
  return <div><Button disabled={busy} variant="secondary" onClick={async () => { setBusy(true); try { const data = await api(`/api/integrations/website/link/${resource}/${record._id}`, { method: 'POST' }); setMessage(data.alreadyLinked ? 'السجل مرتبط بالفعل.' : 'تم الربط بالقسم الحالي.'); } catch (e) { setMessage(e.message); } finally { setBusy(false); } }}>ربط بالقسم الحالي في CRM</Button><p role="status">{message}</p></div>;
}

export default function WebsiteWorkflowPanel({ connection, resource, selected, onRefresh }) {
  const [data, setData] = useState(null), [settings, setSettings] = useState(null);
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const [checks, setChecks] = useState([]), [mails, setMails] = useState([]);
  const [contacts, setContacts] = useState([]), [contact, setContact] = useState(''), [messages, setMessages] = useState([]), [message, setMessage] = useState('');
  async function refresh() { const result = await api('/api/integrations/website/workflow'); setData(result); setSettings(result.settings || { resources: [], recipients: [], identities: {}, autoAssign: false }); }
  useEffect(() => { refresh().catch(e => setError(e.message)); }, []);
  async function run(task) { setBusy(true); setError(''); setNotice(''); try { await task(); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  async function synchronize() { const results = await api('/api/integrations/website/sync', { method: 'POST' }); setChecks(results); await refresh(); onRefresh?.(); setNotice('انتهت قراءة الطلبات. أول قراءة تحفظ خط أساس، والإشعارات تبدأ للطلبات الجديدة بعده.'); }
  async function saveSettings(event) { event.preventDefault(); await run(async () => { await api('/api/integrations/website/workflow/settings', { method: 'PUT', body: JSON.stringify(settings) }); setNotice('تم حفظ إعدادات التوزيع.'); }); }
  async function testCapabilities() { const results = await api('/api/integrations/website/capabilities', { method: 'POST' }); setChecks(results); }
  async function link() { const result = await api(`/api/integrations/website/link/${resource}/${selected._id}`, { method: 'POST' }); setNotice(result.alreadyLinked ? 'السجل مرتبط بالفعل؛ لم تُنشأ نسخة أخرى.' : 'تم ربط السجل بالقسم الحالي دون تعديل السجلات المستقلة.'); await refresh(); }
  async function loadContacts() { setContacts(await api('/api/integrations/website/messaging/contacts')); }
  async function loadMessages(id) { setContact(id); setMessages(id ? await api(`/api/integrations/website/messaging/${id}`) : []); }
  async function send(event) { event.preventDefault(); await run(async () => { await api(`/api/integrations/website/messaging/${contact}`, { method: 'POST', body: JSON.stringify({ body: message }) }); setMessage(''); await loadMessages(contact); }); }
  return <Card>
    <h3>التوزيع والربط والمتابعة</h3>{error && <p role="alert" className="website-error">{error}</p>}{notice && <p role="status" className="website-notice">{notice}</p>}
    <div className="website-toolbar"><Button disabled={busy || !connection?.ready} onClick={() => run(synchronize)}>قراءة الطلبات الجديدة</Button><Button disabled={busy || !connection?.ready} variant="secondary" onClick={() => run(testCapabilities)}>فحص صلاحيات الأقسام</Button>{selected && ['applications', 'students', 'financials', 'events'].includes(resource) && <Button disabled={busy} variant="secondary" onClick={() => run(link)}>ربط بالقسم الحالي في CRM</Button>}</div>
    {checks.length > 0 && <ul>{checks.map(row => <li key={row.resource}>{row.label || row.resource}: {row.ok ? `متاح${row.received == null ? '' : ` — ${row.received} سجل`}` : row.message}</li>)}</ul>}
    {data?.lastSync?.at && <p>آخر متابعة: {formatDate(data.lastSync.at)}</p>}
    <details><summary>إعدادات الإشعارات وتوزيع الموظفين</summary>{settings && <form onSubmit={saveSettings}><p>التوزيع هنا يخص موظفي CRM. تعيين مستشار على الموقع يتم من ملف الطلب.</p><label><input type="checkbox" checked={settings.autoAssign} onChange={e => setSettings(current => ({ ...current, autoAssign: e.target.checked }))} />توزيع الطلبات الجديدة بالتناوب</label>
      <h4>الموظفون المستلمون</h4>{(data?.users || []).map(user => <label className="field" key={user.id}><span><input type="checkbox" checked={settings.recipients.includes(user.id)} onChange={e => setSettings(current => ({ ...current, recipients: e.target.checked ? [...current.recipients, user.id] : current.recipients.filter(id => id !== user.id) }))} /> {user.name}</span><input placeholder="معرّف نفس الموظف بالموقع، اختياري" value={settings.identities?.[user.id] || ''} onChange={e => setSettings(current => ({ ...current, identities: { ...current.identities, [user.id]: e.target.value } }))} /></label>)}
      <h4>أنواع الطلبات المتابَعة</h4>{(connection?.resources || []).filter(row => ['applications', 'services', 'housing', 'arrival', 'consultations', 'scholarships', 'support', 'agencies', 'verification', 'payouts', 'events', 'parents'].includes(row.key)).map(row => <label key={row.key} className="field"><span><input type="checkbox" checked={settings.resources.includes(row.key)} onChange={e => setSettings(current => ({ ...current, resources: e.target.checked ? [...current.resources, row.key] : current.resources.filter(key => key !== row.key) }))} /> {row.label}</span></label>)}<Button disabled={busy} type="submit">حفظ إعدادات التوزيع</Button></form>}</details>
    <details><summary>الطلبات المسندة للموظفين</summary><div className="website-table-wrap"><table className="website-table"><thead><tr><th>الطلب</th><th>صاحب الطلب</th><th>الموظف</th></tr></thead><tbody>{(data?.inbox || []).filter(row => row.resource === resource).slice(-100).reverse().map(row => <tr key={row.id}><td>{row.title || row.resource}</td><td>{row.name}</td><td><select disabled={busy} value={row.ownerId || ''} onChange={e => run(async () => { await api(`/api/integrations/website/inbox/${row.id}/owner`, { method: 'PATCH', body: JSON.stringify({ ownerId: e.target.value }) }); await refresh(); })}><option value="">غير مسند</option>{(data.users || []).map(user => <option key={user.id} value={user.id}>{user.name}</option>)}</select></td></tr>)}</tbody></table></div></details>
    <details><summary>بريد «تواصل معنا»</summary><p>استقبال البريد يتطلب توصيل صندوق البريد بمسار الاستقبال الموضح في دليل الربط.</p><Button disabled={busy} variant="secondary" onClick={() => run(async () => setMails(await api('/api/integrations/website/mail')))}>عرض الرسائل المستلمة</Button>{mails.map(row => <article key={row.id}><h4>{row.subject}</h4><p>{row.name} — {row.email}</p><p style={{ whiteSpace: 'pre-wrap' }}>{row.message}</p></article>)}</details>
    <details><summary>محادثات حساب الموقع المتصل</summary><p>المعروض محادثات الحساب المتصل فقط؛ حساب الاتصال لا ينتحل حسابات الموظفين.</p><Button disabled={busy || !connection?.ready} variant="secondary" onClick={() => run(loadContacts)}>تحميل جهات الاتصال</Button><select aria-label="جهة اتصال الموقع" value={contact} onChange={e => run(() => loadMessages(e.target.value))}><option value="">اختر جهة اتصال</option>{contacts.map(row => <option key={row._id} value={row._id}>{row.name}</option>)}</select>{messages.map(row => <p key={row._id}>{row.body}</p>)}{connection?.writesEnabled && contact && <form onSubmit={send}><textarea aria-label="نص الرسالة" value={message} onChange={e => setMessage(e.target.value)} maxLength={4000} /><Button disabled={busy || !message.trim()} type="submit">إرسال إلى الموقع</Button></form>}</details>
  </Card>;
}
